"""create table students

Revision ID: 791279dd0760
Revises: 6b9cb35ba46e
Create Date: 2022-12-20 10:05:32.829662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791279dd0760'
down_revision = '6b9cb35ba46e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=55), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('enrolled_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###





def upgrade():
    # Rename the column using op.alter_column
        op.alter_column(
        'students',  # Specify the table name
        'name',  # Specify the old column name
        new_column_name='firstname',  # Specify the new column name
        type_=sa.String(255),  # Specify the new column type if changing
        nullable=True,  # Specify the new nullable value if changing
        existing_type=sa.String(255),  # Specify the existing column type
        existing_server_default=None,  # Specify the existing server default if changing
        existing_nullable=True,  # Specify the existing nullable value
    )

